### ISSUE TITLE
alg_list limit 

### ISSUE THREAD

**Issue by abunickabhi** [tao-yu/Alg-Trainer#15]
When I try to feed more algs in the alg-list section, even more than the number of 1LLL algs, the virtual cube freezes up, and doesn't load the next case. https://github.com/abunickabhi/5style-Trainer/blob/master/js/alg_list.js

I want to find a workaround to fix this issue so that all the algs will be loaded up and can be drilled sequentially. For the time being, I am breaking up the alg lists into various sections, like 10a, 10b and so on.

**Comment by tao-yu** [comment]
Closing this issue because I have discussed this with you already in private chat.

(By memory I think the issue was that the move count calculator is slow for extremely large algset like 5-style)
