### ISSUE TITLE
Issue connecting my Rubik's Connect

### ISSUE THREAD

**Issue by DaPuzzles** [tao-yu/Alg-Trainer#16]
I wished to use my Rubik's Connect on here to improve my knowledge of alg cases but when I clicked the "Connect Giiker Cube" button it can't find my cube while I can connect it to other sites just fine. I were just wondering if its an issue at your end or if I'm just being an idiot. (highly likely)

**Comment by tao-yu** [comment]
Only Giiker brand cubes are supported (the button reads "Connect Giiker cube" not "Connect Bluetooth cube"). Rubik's connect, Gan i and GoCube are not giiker cubes so they will not work with this site.

I'm really sorry that you won't be able to use your cube with my site. I realise that it could be made more clear that some bluetooth cubes are no supported, so I'll add a message that makes it more clear on the site
