### ISSUE TITLE
Possible to avoid initial x rotations?

### ISSUE THREAD

**Issue by elucid** [tao-yu/Alg-Trainer#24]
Hello, if I use the following algorithm `U' r U' M U r' U'` with "Use Real Scrambles", "Random AUF", "Scramble Subsequent Steps", "Full colour neutrality", and all of the "Starting from WCA orientation:..." boxes unchecked, I get `x' U r U' M' U r' U` as my scramble when I would have expected `U r U' M' U r' U`. Why do I sometimes get initial x rotations? Is it possible to avoid this? Thanks.

**Comment by tao-yu** [comment]
Very late, but I have added an option to disable automatic rotation fixing. This feature was originally intended to make algs like x R' U R' D2 R U' R' D2 R2 which omit the final rotation to work with the custom algs feature. However, I see the utility of giving users the option to disable this behaviour.
